kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-centos-1
spec:
  storageClassName: vxflexos
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-centos-2
spec:
  storageClassName: vxflexos
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
